#!/usr/bin/env bash
# Runs once when the Codespace/devcontainer is created. Deliberately fast and
# offline: it writes a demo config and seeds synthetic data, both instant.
# It does NOT run tools/build_reference_data.php - that needs the network and
# can take a while (a 900 KB PDF to parse for the Czech tables alone), and
# buys nothing for the demo: src/data/cdc.php already ships, and
# tools/seed_demo_data.php only uses that one. Want the others too? Run
# `php tools/build_reference_data.php` yourself once the Codespace is up.
set -euo pipefail
cd "$(dirname "$0")/.."

cat > src/config.php <<'PHP'
<?php
/* Generated by .devcontainer/postCreate.sh - a demo instance, not a real
 * deployment. Do not copy $RUST_AUTH_HANDLED_EXTERNALLY into a real one:
 * it is justified here only because GitHub Codespaces forwards ports as
 * private by default, requiring a GitHub login with access to this
 * Codespace - that external check is what src/auth.inc would otherwise be
 * providing itself. A self-hosted install has no such thing in front of it
 * and needs its own Basic Auth (see README.md).
 */
$STORAGE_BACKEND = 'json';
$DEMO_MODE = true;
$RUST_AUTH_HANDLED_EXTERNALLY = true;
PHP

php tools/seed_demo_data.php
echo "Demo data seeded. The app will be available on the forwarded 8080 port once the container starts."
